oneibmcloud/DevOps-Insights#5126 updated pipelines and policy json

diff --git a/.bluemix/catalog-api.pipeline.yml b/.bluemix/catalog-api.pipeline.yml
--- a/.bluemix/catalog-api.pipeline.yml
+++ b/.bluemix/catalog-api.pipeline.yml
@@ -20,6 +20,14 @@ stages:
   jobs:
   - name: Build
     type: builder
+    artifact_dir: ''
+    build_type: shell
+    script: |-
+      #!/bin/bash
+      # your script here
+      export PATH=/opt/IBM/node-v4.2/bin:$PATH
+        npm install -g npm@3.7.2 ### work around default npm 2.1.1 instability
+        npm install
   - name: Unit Tests
     type: tester
     enable_tests: true
@@ -96,7 +104,7 @@ stages:
       space: ${STAGING_SPACE_NAME}
       application: ${CF_APP_NAME}
       api_key: ${API_KEY}
-    script: |
+    script: |-
       #!/bin/bash
       export PATH=/opt/IBM/node-v4.2/bin:$PATH
 
@@ -129,6 +137,52 @@ stages:
       fi
       npm install -g grunt-idra3
       idra --publishdeployrecord  --env=$LOGICAL_ENV_NAME --status=$deploy_status --appurl=$APP_URL
+  - name: FVT Test
+    type: tester
+    script: |-
+      #!/bin/bash
+      GRUNTFILE="tests/Gruntfile.js"
+      if [ -f $GRUNTFILE ]; then  
+        export PATH=/opt/IBM/node-v4.2/bin:$PATH  
+        npm install -g grunt-idra3
+        export CATALOG_API_TEST_SERVER=${APP_URL} 
+
+        set +e  
+        grunt dev-fvt --no-color --gruntfile $GRUNTFILE --base .  
+        grunt_result=$?  
+        set -e  
+        
+        idra --publishtestresult --filelocation=./tests/fvt/mochafvttest.xml --type=fvt  
+        if [ $grunt_result -ne 0 ]; then     
+          exit $grunt_result  
+        fi
+      else  
+        echo "$GRUNTFILE not found."
+      fi
+    test_type: simple
+  - name: Integration Test
+    type: tester
+    script: |-
+      #!/bin/bash
+      GRUNTFILE="tests/Gruntfile.js"
+      if [ -f $GRUNTFILE ];then  
+        export PATH=/opt/IBM/node-v4.2/bin:$PATH  
+        npm install -g grunt-idra3
+        export CATALOG_API_TEST_SERVER=${APP_URL}  
+        
+        set +e  
+        grunt dev-integration-test --no-color --gruntfile $GRUNTFILE --base .  
+        grunt_result=$?  
+        set -e
+
+        idra --publishtestresult --filelocation=./tests/integration_tests/mocha_integration_test.xml --type=integrationtest  
+        if [ $grunt_result -ne 0 ]; then     
+          exit $grunt_result
+        fi
+      else
+        echo "$GRUNTFILE not found."
+      fi
+    test_type: simple
     enable_tests: false
     test_file_pattern: ''
 - name: PRODUCTION
diff --git a/.bluemix/orders-api.pipeline.yml b/.bluemix/orders-api.pipeline.yml
--- a/.bluemix/orders-api.pipeline.yml
+++ b/.bluemix/orders-api.pipeline.yml
@@ -25,9 +25,34 @@ stages:
     script: |-
       #!/bin/bash
       export PATH=/opt/IBM/node-v4.2/bin:$PATH
-      npm install -g grunt-idra3
+        npm install -g npm@3.7.2 ### work around default npm 2.1.1 instability
+        npm install
+  - name: Test
+    type: tester
+    script: |-
+      #!/bin/bash
+      GRUNTFILE="tests/Gruntfile.js"
+      if [ -f $GRUNTFILE ]; then
+        export PATH=/opt/IBM/node-v4.2/bin:$PATH
+        npm install -g npm@3.7.2 ### work around default npm 2.1.1 instability
+      npm install
+        npm install -g grunt-idra3
 
-      idra --publishbuildrecord --branch=$GIT_BRANCH --repositoryurl=$GIT_URL --commitid=$GIT_COMMIT --status="pass"
+        set +e
+        grunt dev-test-cov --no-color --gruntfile $GRUNTFILE --base .
+        grunt_result=$?
+        set -e
+
+        idra --publishtestresult --filelocation=./tests/server/mochatest.xml --type=unittest
+        idra --publishtestresult --filelocation=./tests/server/coverage/reports/coverage-summary.json --type=code
+
+        if [ $grunt_result -ne 0 ]; then
+           exit $grunt_result
+        fi
+      else
+        echo "$GRUNTFILE not found."
+      fi
+    test_type: simple
 - name: STAGING
   inputs:
   - type: job
@@ -98,6 +123,52 @@ stages:
       idra --publishdeployrecord  --env=$LOGICAL_ENV_NAME --status=$deploy_status --appurl=$APP_URL
     enable_tests: false
     test_file_pattern: ''
+  - name: FVT Test
+    type: tester
+    script: |-
+      #!/bin/bash
+      GRUNTFILE="tests/Gruntfile.js"
+      if [ -f $GRUNTFILE ]; then  
+        export PATH=/opt/IBM/node-v4.2/bin:$PATH  
+        npm install -g grunt-idra3
+        export CATALOG_API_TEST_SERVER=${APP_URL} 
+
+        set +e  
+        grunt dev-fvt --no-color --gruntfile $GRUNTFILE --base .  
+        grunt_result=$?  
+        set -e  
+        
+        idra --publishtestresult --filelocation=./tests/fvt/mochafvttest.xml --type=fvt  
+        if [ $grunt_result -ne 0 ]; then     
+          exit $grunt_result  
+        fi
+      else  
+        echo "$GRUNTFILE not found."
+      fi
+    test_type: simple
+  - name: Integration Test
+    type: tester
+    script: |-
+      #!/bin/bash
+      GRUNTFILE="tests/Gruntfile.js"
+      if [ -f $GRUNTFILE ];then  
+        export PATH=/opt/IBM/node-v4.2/bin:$PATH  
+        npm install -g grunt-idra3
+        export CATALOG_API_TEST_SERVER=${APP_URL}  
+        
+        set +e  
+        grunt dev-integration-test --no-color --gruntfile $GRUNTFILE --base .  
+        grunt_result=$?  
+        set -e
+
+        idra --publishtestresult --filelocation=./tests/integration_tests/mocha_integration_test.xml --type=integrationtest  
+        if [ $grunt_result -ne 0 ]; then     
+          exit $grunt_result
+        fi
+      else
+        echo "$GRUNTFILE not found."
+      fi
+    test_type: simple
 - name: PRODUCTION
   inputs:
   - type: job
